### ISSUE TITLE
Error when I ask a way by its ID

### ISSUE THREAD

**Issue by fbroussais** [mvexel/overpass-api-python-wrapper#102]
Hello,

I ask this simple query :

`response = api.get("way(229416587)", responseformat="geojson")`

And I get the error : **UnboundLocalError: local variable 'geometry' referenced before assignment**
I get the same error with **responseformat="xml"**, but **no error with "json"** (and I receive the good data).

Do I make a mistake ?

**Comment by mvexel** [comment]
I tried the exact same query just now and it worked just fine. Can you try again?

**Comment by mvexel** [comment]
Perhaps this was an error related to an older version. I am going to close this assuming that was the case, but feel free to re-open if I misunderstood your issue.

**Comment by fbroussais** [comment]
Sorry I had no time to test. I'll reopen if necessary.
Thank you !
