### ISSUE TITLE
Write result to file

### ISSUE THREAD

**Issue by antifa-ev** [mvexel/overpass-api-python-wrapper#103]
How can I dump the result to a GeoJSON file?

When there are [nested FeatureCollections](https://gis.stackexchange.com/questions/171230/how-do-you-read-write-a-featurecollection-from-to-a-json-file) the output via geojson.dump is faulty!

**Comment by mvexel** [comment]
Hey, let's solve this. Can you give an example?

**Comment by mvexel** [comment]
The example you link to is not valid GeoJSON:

```
{
  "type": "FeatureCollection", 
  "features": {
    "type": "FeatureCollection", 
    "features": [
      {
        "geometry": {
          "type": "Polygon", 
          "coordinates": [
            [

            ]
          ]
        }, 
        "type": "Feature", 
        "properties": {
          "gval": 1.0, 
          "hectares": 0.218681933167, 
          "xid": 0, 
          "id": 1.0, 
          "area": 2186.81933167
        }
      }
    ]
  }
}
```
has a dictionary as the value for `features` and as far as I know this is not valid according to GeoJSON spec.

**Comment by mvexel** [comment]
Closing this because no more feedback for some time. Feel free to reopen @antifa-ev if you feel your question was not answered!
