### ISSUE TITLE
Behavior of "out geom"

### ISSUE THREAD

**Issue by uswoods** [mvexel/overpass-api-python-wrapper#106]
When I don't use out geom I'm getting an error (see below), but when I use it, the json output is [duplicated](https://pastebin.com/9yeiLrw5). Am I utilizing the option in a wrong matter?

```
import json
import overpass

endpoint = "https://overpass-api.de/api/interpreter"
api = overpass.API(timeout=100, endpoint=endpoint)
way = '45667934'
query = 'way('+str(way)+');out geom;'
result = api.get(query, responseformat="geojson")
print(result)
```

Error:
>     UnboundLocalError: local variable 'geometry' referenced before assignment

**Comment by mvexel** [comment]
This example seems to [run fine](https://repl.it/repls/StaidDrabScripts). Make sure you have the latest version of the module.

Just a few pointers if I may:
* If you want to set the output verbosity to something else than the default `body`, use the `verbosity` parameter of the `get` call. See the relevant [documentation](https://github.com/mvexel/overpass-api-python-wrapper#verbosity).
* You don't need to set the interpreter if you're sticking with the default.

**Comment by uswoods** [comment]
But sorry, it runs fine but has duplicate geometry:

Geometry I
```
{
  "features": [
    {
      "geometry": {
        "coordinates": [
          [
            4.2711979,
            51.3542058
          ],
          ...
        ],
        "type": "LineString"
      },
      "id": 45667934,
      "properties": {
        "addr:housenumber": "600",
        "addr:postcode": "2040",
        "addr:street": "Scheldelaan",
        "alt_name": "BASF",
        "landuse": "industrial",
        "man_made": "works",
        "name": "BASF Antwerpen nv",
        "website": "http://www.basf.be",
        "wikipedia": "nl:BASF (chemieconcern)"
      },
      "type": "Feature"
    },
```
Geometry II
 ```
   {
      "geometry": {
        "coordinates": [
          [
            4.2711979,
            51.3542058
          ],
          ...
        ],
        "type": "LineString"
      },
      "id": 45667934,
      "properties": {
        "addr:housenumber": "600",
        "addr:postcode": "2040",
        "addr:street": "Scheldelaan",
        "alt_name": "BASF",
        "landuse": "industrial",
        "man_made": "works",
        "name": "BASF Antwerpen nv",
        "website": "http://www.basf.be",
        "wikipedia": "nl:BASF (chemieconcern)"
      },
      "type": "Feature"
    }
  ],
  "type": "FeatureCollection"
}
```

**Comment by mvexel** [comment]
That is because you use `out geom` in your query instead of using `verbosity='geom' in the `get()` call:

```
import overpass
api = overpass.API()
query = 'way(45667934);'
result = api.get(query, verbosity='geom')
print(result)
```

gets you

```
{"features": [{"geometry": {"coordinates": [[4.2711979, 51.3542058], [4.2690866, 51.3543414],... [4.287715, 51.353279], [4.2870876, 51.3533091], [4.2804398, 51.3536934], [4.2798607, 51.353716], [4.2747813, 51.3540099], [4.2711979, 51.3542058]], "type": "LineString"}, "id": 45667934, "properties": {"addr:housenumber": "600", "addr:postcode": "2040", "addr:street": "Scheldelaan", "alt_name": "BASF", "landuse": "industrial", "man_made": "works", "name": "BASF Antwerpen nv", "website": "http://www.basf.be", "wikipedia": "nl:BASF (chemieconcern)"}, "type": "Feature"}], "type": "FeatureCollection"}
```

I updated the code in the repl as well.

**Comment by mvexel** [comment]
Does it work for you now @uswoods ?

**Comment by mvexel** [comment]
`overpass` will output a `FeatureCollection`, so if you want to access its individual geometries you will have to access its `features` dict:

```python
import overpass
from shapely.geometry import shape, Polygon
api = overpass.API()
query = 'way(45667934);'
result = api.get(query, verbosity='geom')
linestring = shape(result.features[0].geometry)
poly = Polygon(linestring)
print(poly.area)
```

**Comment by uswoods** [comment]
Thanks for the solution. But there is something weird:

According to JOSMs measurement plugin [BASF Antwerp](https://www.openstreetmap.org/way/45667934) has a size of 606 hectares. Shapely gives 609 after projecting. `poly.area` gives 0.0007859869400399928
- Why ?

**Comment by uswoods** [comment]
And when I query for a multipolygon, the output is empty:

```
import overpass
api = overpass.API()
query = 'relation(2688333);'
result = api.get(query, verbosity='geom')
print(result)
```

**Comment by mvexel** [comment]
Relations are not supported in `overpass` yet. See #48.

**Comment by uswoods** [comment]
@mvexel I've now patched my local overpass version that relations do indeed work thanks to @t-g-williams work.

The polygon itself could be read by Shapely, but it's complaining due to the FeatureCollection. How can I remove the FeatureCollection from the GeoJSON's "DOM tree"? (Where should I better ask this question? On StackOverflow it was deleted)
