### ISSUE TITLE
Returns null geometries

### ISSUE THREAD

**Issue by paumillet** [mvexel/overpass-api-python-wrapper#116]
Hello,

From not I was only using Overpass API Python wrapper for querying nodes. I would like to use it now for querying ways and I got back only null geometries.

Here my code:
```python
query_text = 'area(3602134786)->.a;(nwr[leisure~"^(park)$"](area.a););'
api = overpass.API()
result = api.get(query_text)
```
And an extract of what I got returned:
```geojson
{"features": [
{"geometry": null,
"id": 51876557,
"properties": {"barrier": "fence", "leisure": "park", "name": "Parc Wilson"},
"type": "Feature"
},
{"geometry": null,
"id": 51925873,
"properties": {"barrier": "fence", "leisure": "park", "name": "Parc Napol\u00e9on", "ref:FR:FANTOIR": "576721870A"},
"type": "Feature"
},
{"geometry": null,
"id": 65283729,
"properties": {"leisure": "park", "name": "Square Robert Schuman", "source": "cadastre-dgi-fr source : Direction G\u00e9n\u00e9rale des Imp\u00f4ts - Cadastre. Mise \u00e0 jour : 2010"},
"type": "Feature"
}, 
...
], "type": "FeatureCollection"}
```

When I do the exact same request using Python librairy `requests`, I actually got non null geometries:
```python
import requests
import json

overpass_url = "http://overpass-api.de/api/interpreter"
query_text = 'area(3602134786)->.a;(nwr[leisure~"^(park)$"](area.a););'

response = requests.get(overpass_url, 
                        params={'data': query_text})

data = response.json()
```

Any idea of what is going wrong?

Thanks for your help,

Pauline

**Comment by frodrigo** [comment]
The conversion to geojson of relations and areas are not supported.

**Comment by fchabouis** [comment]
That's too bad...maybe a little disclaimer in the doc would save some people time ? I got really confused trying to output geojsons for a subway line. Thanks !

**Comment by paumillet** [comment]
I actually found the trick after having spent days in the docs and the code: 
You need to add the parameter **`verbosity="geom"`** when passing your request as in the following example.
```
query_text = 'area(3602134786)->.a;(nwr[leisure=park](area.a););'
api = overpass.API()
result = api.get(query_text, responseformat="geojson", verbosity="geom")
```

Hope it helps!

**Comment by fchabouis** [comment]
Thanks @paumillet but unfortunately it's not working for me.
```
overpass_query = '''
relation["route"="subway"](48.81320833138744,2.3525333404541016,48.825599002995716,2.3743772506713867);
'''
response = api.get(overpass_query, responseformat="geojson", verbosity="geom")
```
yields an empty response. But the same query in [overpass turbo](https://overpass-turbo.eu/s/P8H) gives a full response.

**Comment by paumillet** [comment]
Yes, I actually have the same issue today, but it was perfectly working all week long...
