### ISSUE TITLE
Commit 603b7ec to master broke the library

### ISSUE THREAD

**Issue by Taxuspt** [mvexel/overpass-api-python-wrapper#119]
Commit https://github.com/mvexel/overpass-api-python-wrapper/commit/603b7ec1818befa780eb6f0389eb7b71db17dcfe which was merged to master has broken the library when dealing with geojson data.
It makes the following, wrong assumptions:

- Ways and Relations contain a `geometry` field: That only happens if you call `get()` with `verbosity='body geom'`
- All the geometries inside a relation are closed polygons: That is only one of the options, as can be seen in the [official documentation](https://wiki.openstreetmap.org/wiki/Relation:multipolygon).

Please revert this commit. For proper parsing from OSM to GEOJSON you could use [osm2geojson](https://github.com/aspectumapp/osm2geojson).

**Comment by mvexel** [comment]
We are doing this now (finally) with #140 merged.
Once we get 0.7.1 out with this improvement I think this can be closed.
