### ISSUE TITLE
Amenities in radius of coordinates using overpassturbo /OSM

### ISSUE THREAD

**Issue by ulan123** [mvexel/overpass-api-python-wrapper#121]
Hi All, I have data with columns latitude and longitude (data.xlsx).it has 17K observations. I want to search for amenities around 1000 meters for each address in my dataset. Later I want to calculate difference from this address to each of the obtained amenities per address and create new column with their average value.  
I am quite new to request codes in Python, so I know how to do it for one address (lat, lon), but could someone help how to do it for all 17K?  

import requests
import json
overpass_url = "http://overpass-api.de/api/interpreter"
overpass_query = """
[out:json];
(
node(around:900.0,52.2438559,20.91043506290992)["amenity"~"^(cafe|restaurant|bar)$"];
);
out body;
    """
 
response = requests.get(overpass_url,
                        params={'data': overpass_query})
response.json()

**Comment by mvexel** [comment]
This is more of a general Overpass API question. Best to try OSM communications channels.
