### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by mvexel** [mvexel/overpass-api-python-wrapper#137]
I started this project to scratch an itch and have done my best to maintain it, but I simply don't have the time anymore. The project seems well liked and used, and I think it's a shame that it's poorly maintained. So I'm looking for someone else to take ownership. Let me know if you're interested and we can chat.

**Comment by baditaflorin** [comment]
Hi Martijn, can you explain what your would be the role of that person, what would be your expectation for the maintainer.

**Comment by mvexel** [comment]
The project maintainer needs to be in complete charge of the future direction of the project, including roadmap planning, architectural decisions, issue and PR review, and actively collaborating with the other active contributors.

Some things that you will definitely need:
* Great Python programming skills
* Understanding of the Python ecosystem (to assess dependencies, Python versions to support
* Understanding of testing / TDD
* Good knowledge of the Overpass API
* Experience as an OSS maintainer, preferably in the geospatial / OSM domain

I have most of these things, just not the time to properly apply them to this project. But my personal situation has changed a bit so I can devote a bit more time to this project again, so no rush for the moment!

**Comment by metazool** [comment]
Hi Martijn, I'd like to use this library in a project, and it would be good for me to have a small commitment while I have some free time. I'd be happy to take on some maintenance responsibility and work through some of the outstanding PRs...

**Comment by mvexel** [comment]
That's awesome, thanks! Do you want to have a chat about the project sometime? Are you on any OSM communications channels?

**Comment by metazool** [comment]
I'm not, is there anywhere you'd recommend joining? Apart from trying to triage issues does the __geo_interface__ one look like a good place to contribute as a proof of faith?

**Comment by mvexel** [comment]
sure! On my end I will do my best to monitor the repo here. Happy to discuss whatever questions may come up.

Comms: I've enjoyed slack.openstreetmap.us

**Comment by mvexel** [comment]
I have some capacity to pick things up again.

My plan is to do these things in order:
1. Go through open PRs and address any concerns, merge small ones quickly, #160 #159  and #156 could be done pretty quickly
2. Once that is done, get a point release 0.7.1 out and publish to pypi
3. Go through open issues and triage. Perhaps make a kanban board to organize?
4. Look at project hygiene -- test coverage, code conventions, update README 

I think that would be a good start? I'm happy to meet with a few folks and discuss. @metazool @dericke , others?

**Comment by mvexel** [comment]
I started a "refresh" branch https://github.com/mvexel/overpass-api-python-wrapper/compare/main...refresh to do some minor cleanup (README update, some code formatting / hygiene) but I don't want to prioritize this over steps 1 2 3.. That's just me trying to get back into the code base .. Feel free to ignore for now.

**Comment by mvexel** [comment]
I am closing this for the moment as I am rededicating some of my time to this project
