### ISSUE TITLE
Test failing for 3.6

### ISSUE THREAD

**Issue by dericke** [mvexel/overpass-api-python-wrapper#138]
My use of `datetime.strptime()` in #134 relied on a Python 3.7+ feature, something I didn't realize until seeing the failing 3.6 tests today. Would it be better to drop 3.6 support, or should I refactor to remove the 3.7 dependency?

**Comment by mvexel** [comment]
I would be okay with dropping support for 3.6, I think it reaches some EOL by the end of '21 anyway.

**Comment by Vitalts** [comment]
Here added fix for 3.6 https://github.com/mvexel/overpass-api-python-wrapper/pull/144
