### ISSUE TITLE
Wrapper doesn't return OSM Feature version.

### ISSUE THREAD

**Issue by viksuper555** [mvexel/overpass-api-python-wrapper#155]
### Introduction:
Each feature in OSM contains a version property of type int, which defines how many changes were applied to the feature.
![image](https://user-images.githubusercontent.com/15073936/217563275-7a82177e-9050-455f-9220-69e2c61fd7d4.png)

### Problem:
This property is currently not passed back to the caller, even with the verbosity="meta" flag.

### Reproduction sample:
api = overpass.API(timeout=500)
response = api.get('way[name="Belsenplatz"];', responseformat="geojson", verbosity="meta")

#### Expectations:
response.get('features')[0] to contain the version property. It currently doesn't.

**Comment by mvexel** [comment]
If you request an element with `verbosity="meta"` you do get the OSM version number as well as the other OSM metadata elements:

```
>>> api.get("node(1)", verbosity="meta")
{"features": [{"geometry": {"coordinates": [13.569003, 42.795719], "type": "Point"}, "id": 1, "properties": {"communication:microwave": "yes", "communication:radio": "fm", "description": "Radio Subasio", "frequency": "105.5 MHz", "man_made": "mast", "name": "Monte Piselli - San Giacomo", "tower:construction": "lattice", "tower:type": "communication", "uid": 29598, "user": "owene", "version": 33}, "type": "Feature"}], "type": "FeatureCollection"}
```
