### ISSUE TITLE
submit to PyPi

### ISSUE THREAD

**Issue by mvexel** [mvexel/overpass-api-python-wrapper#16]
Never done before, what more would be required to do this?

This seems relevant: https://packaging.python.org/en/latest/distributing.html

**Comment by willemarcel** [comment]
I published it to pypi: https://pypi.python.org/pypi/overpass

I put my github repository, because it's the most updated.

**Comment by mvexel** [comment]
We should decide which repo is the master, and thad repo should be in sync
with PyPi. I prefer this to be that repository, because yours is a fork. We
should merge any upstream changes into this master first, so we can all
keep track of what is going on. Sound good?

Martijn van Exel
skype: mvexel

**Comment by willemarcel** [comment]
Of course, It's good for me! I've updated the package in Pypi with reference to your repository and gave you owner rights.

**Comment by mvexel** [comment]
Best to send a pull request with changes from your fork to this repo so we can all review and then submit from here, does that sound good? Thanks @willemarcel

**Comment by willemarcel** [comment]
There is already a pull request: https://github.com/mvexel/overpass-api-python-wrapper/pull/27

**Comment by mvexel** [comment]
That's right, sorry for the confusion...

Martijn van Exel
skype: mvexel

**Comment by gEndelf** [comment]
@mvexel  Plz

* update README
* and this issue can be closed

**Comment by willemarcel** [comment]
Hi, @gEndelf and @mvexel 

I updated the README on my fork and I made a pull request some months ago (#27)

**Comment by mvexel** [comment]
Hi, just checking in here I see that there is version 0.3.1 on PyPi, however the master repo only has a 0.1.0. We should try and merge that code back in, I think this is confusing. @willemarcel is that your fork?

**Comment by mvexel** [comment]
New PR at #36  - please review!

**Comment by mvexel** [comment]
Let's prepare a new release now that @willemarcel 's code is merged in, and I made some changes that affect end users (to the CLI interface and to the `responseformat` parameter)

**Comment by sandrotosi** [comment]
@mvexel could you cut a new release and upload it to pypi? there has been quite a few improvements since 0.3.1 - thanks!

**Comment by mvexel** [comment]
Done. 0.4.0 now on PyPi
