### ISSUE TITLE
Output formats

### ISSUE THREAD

**Issue by Skippern** [mvexel/overpass-api-python-wrapper#28]
I notice that it only accept json output format, while I would like to have the output in XML. Could the other output options be available as well?

**Comment by itiboi** [comment]
We could add this as option, is there a specific reason why you need it? I am not very experienced with using XML in Python. Do you think about getting a parsed answer (e.g. as ElementTree) or a raw response?

**Comment by Skippern** [comment]
I had idea to work with XML as I am more familiar with that, but have worked my head around it, and now parsing it in JSON, though the final output is an XML osmChange file. I guess getting different responses depend on what is planned to do with the output.

**Comment by willemarcel** [comment]
Hi, @Skippern 
I developed this feature this week on my fork. See the README for the instructions on how to use it: https://github.com/willemarcel/overpass-api-python-wrapper

**Comment by mvexel** [comment]
#36 resolves this
