### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by mvexel** [mvexel/overpass-api-python-wrapper#29]
Hi all, 

I have too little time to maintain this project properly. Who would be interested in sharing this responsibility? @itiboi perhaps?

**Comment by itiboi** [comment]
I unfortunately also lack of much free time, but if maintaining is shared I am happy to help!

**Comment by mvexel** [comment]
OK added you as a collaborator. You should now be able to merge PRs and manage the project. Thanks!

**Comment by mvexel** [comment]
Closing this for now.
