### ISSUE TITLE
Crashes with the following parameters

### ISSUE THREAD

**Issue by Xevib** [mvexel/overpass-api-python-wrapper#33]
api.Get('(node["amenity"="hospital"](around:10000,41.978387,2.81353);way["amenity"="hospital"](around:10000,41.978387,2.81353);relation["amenity"="hospital"](around:10000,41.978387,2.81353););out body center;',asGeoJSON=True)

**Comment by itiboi** [comment]
As the exception type OverpassSyntaxError indicates, your request contains syntax error. Please take a closer look at the [Overpass language syntax](http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide) for this.
