### ISSUE TITLE
searchString with ;out meta; give double positives

### ISSUE THREAD

**Issue by Skippern** [mvexel/overpass-api-python-wrapper#46]
I notice that the search string URL automatically adds `out body`, this results that my search with `out meta` in the string returns double positives (each object two times with different level on appended data). Would it be possible to drop the auto-append of `out body` when search string ends with other `out` statements?

**Comment by Guibod** [comment]
+1

**Comment by itiboi** [comment]
This feature was implemented in #47, so beginning with version 0.4.0 you are able to set the desired verbosity with the respective argument of the Get() function.
