### ISSUE TITLE
please consider including tests/ dir in pypi release

### ISSUE THREAD

**Issue by sandrotosi** [mvexel/overpass-api-python-wrapper#50]
Hello,
i noticed the github repo has a tests/ directory, while the tarball on pypi doesnt: could you consider adding it? it would be helpful for distributions to verify everything is working as expected and generally it's a nice practice to be able to run tests of a third-party modules.

thanks for considering,
Sandro

**Comment by mvexel** [comment]
Could you supply the necessary changes to `setup.py` and / or `setup.cfg`?

**Comment by sandrotosi** [comment]
thanks!! do you mind adding also the `examples/` directory? i still dont see `tests/` in 0.6.0 (as released on PyPI) so hopefully the next release :)

**Comment by mvexel** [comment]
finally! :)

**Comment by sandrotosi** [comment]
thanks a lot! it looks like `tests/__pycache__/test_api.cpython-27-PYTEST.pyc` sneaked into the PyPI tarball release. it's no big deal at all, but you may want to release only source code the next time :)
