### ISSUE TITLE
API(debug=True) is not python3 compatible

### ISSUE THREAD

**Issue by sandrotosi** [mvexel/overpass-api-python-wrapper#53]
```
In [39]: api = overpass.API(timeout=3600, debug=True)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-39-67bc1e87daf5> in <module>()
----> 1 api = overpass.API(timeout=3600, debug=True)

/usr/lib/python3/dist-packages/overpass/api.py in __init__(self, *args, **kwargs)
     26 
     27         if self.debug:
---> 28             import httplib
     29             import logging
     30             httplib.HTTPConnection.debuglevel = 1

ImportError: No module named 'httplib'
```

thats because `httplib` has been renamed to `http.client` in py3k, so the usual try/import/except/import dance is needed here

**Comment by itiboi** [comment]
Was fixed with 3ea6db13980c4ee4c2a4a8b9d9ff751bc8c282a7.

**Comment by sandrotosi** [comment]
thanks! it would be great if you could release a new version with that fix, so debian can pick that up

**Comment by itiboi** [comment]
Any plans for this @mvexel? I was no active for a long time, so I do not how much has changed since the last version.

**Comment by mvexel** [comment]
Yes, a new release is due. I will take care of it shortly, but I want to go
over open tickets to see if there's any that can be easily addressed before
we do. Can you help out?
