### ISSUE TITLE
not possible to use the recurse operator in OSM query

### ISSUE THREAD

**Issue by sandrotosi** [mvexel/overpass-api-python-wrapper#54]
as query is composed, there is always a `out body geom` at the end of it, so it looks like it's not possible to use specify the recurse operator, at least based on what overpass translator proposes, which is `<query>;out body;>;out skel;`

**Comment by mvexel** [comment]
You can pass `build=False` to your `get()` call to circumvent the module's 'smart' behavior. In that case you just pass a full Overpass query in. 
Let me know if that works for you!
