### ISSUE TITLE
Known maximum length of number of ways/nodes to request in single query

### ISSUE THREAD

**Issue by eoglethorpe** [mvexel/overpass-api-python-wrapper#66]
Seems that overpass will only accept a maximum of 1023 elements per query.

For instance this works fine:

```
import overpass
api = overpass.API()

#t looks something like (node(-1); node(-1)...;)
t = ('(' + ';'.join(['way(-1)' for v in xrange(0,1023)]) + ';)')
api.Get(t)`
```

But this gives an `OverpassSyntaxError`:

```
t = ('(' + ';'.join(['way(-1)' for v in xrange(0,1024)]) + ';)')
api.Get(t)`
```

I can't seem to find anything documentation on the maximum number of elements you can query at once. It would be nice to have a more detailed error if this is an exception that can be specifically handled

**Comment by mmd-osm** [comment]
That's a bug in Overpass API, actually.

**Comment by mmd-osm** [comment]
That bug has been fixed in the meantime, but somehow Roland forgot to include this patch in the overpass-api.de deployment.  @drolbr

**Comment by mvexel** [comment]
@mmd-osm I am guessing this should no longer be an issue?

**Comment by mmd-osm** [comment]
Right, this issue can be closed, it has been fixed upstream.
