### ISSUE TITLE
Is it possible to get the boundary coordinates?

### ISSUE THREAD

**Issue by ssilwa** [mvexel/overpass-api-python-wrapper#73]
The overpass API mentions that it is possible to get the boundary coordinates of a location, for example, a city. I cannot figure out how to do this through this python module. Can anyone help me?

**Comment by trypy** [comment]
Added following example under a fork:
https://github.com/trypy/overpass-api-python-wrapper/blob/d921bf95b54a91fd7827ae34205665640d7d4a19/examples/boundary_nodes_city_ISO3166-1_US.py

Please let me know if helpful.  Only tested on one city.

**Comment by wpfan2099** [comment]
loooks great - dar trypy thaks for sharing

**Comment by mvexel** [comment]
Can you supply an example Overpass query @ssilwa ?

**Comment by mvexel** [comment]
I think you mean `out bb`?

You can do this today with a raw query:

```python
>>> import overpass
>>> api = overpass.API()
>>> resp = api.get("""[out:json];relation[name="Amsterdam"];out bb;""", build=False, responseformat="json")
>>> resp["elements"][0]["bounds"]
```

**Comment by mvexel** [comment]
I think my answer addresses OPs issue, but haven't heard back. I will close this but please re-open if you have additional questions @ssilwa.
