### ISSUE TITLE
In import please substitute httplib module with http.client module

### ISSUE THREAD

**Issue by marcobra** [mvexel/overpass-api-python-wrapper#77]
Hi trying to run the code with debug, if i set debug on 

in api = overpass.API(timeout=600, debug=True) 

i get httplib module import error

to made it works in the file /usr/local/lib/python3.5/dist-packages/overpass/api.py

i must set this code
import http.client 

and then i must change:
httplib.HTTPConnection.debuglevel = 1

with
http.client.HTTPConnection.debuglevel = 1

as below:
...
       if self.debug:
            import http.client
            import logging
            http.client.HTTPConnection.debuglevel = 1
...

**Comment by mvexel** [comment]
Could you elaborate? Which Python version? Why are you missing httplib?

If it makes sense I'd take a PR :)

**Comment by marcobra** [comment]
i've update original message ... 
i hope is more clear now ...

**Comment by mvexel** [comment]
This has been fixed. Tested and works in Python 3.5
