### ISSUE TITLE
Support for PBF format

### ISSUE THREAD

**Issue by CMCDragonkai** [mvexel/overpass-api-python-wrapper#78]
https://github.com/drolbr/Overpass-API/issues/339

**Comment by mvexel** [comment]
That would be cool! I lack the time currently but keeping this open for sure.

**Comment by mvexel** [comment]
I see this is still open on the Overpass side, not much to do until that's done on that side.

Thinking about this, I am not quite sure what 'support' for PBF would look like. Could you elaborate @CMCDragonkai ?

**Comment by CMCDragonkai** [comment]
That the python api could output PBF as well as a format.
