### ISSUE TITLE
TypeError: getresponse() got an unexpected keyword argument 'buffering'

### ISSUE THREAD

**Issue by matkoniecz** [mvexel/overpass-api-python-wrapper#82]
on timeout of extra-long query I got this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
```

code: https://gist.github.com/matkoniecz/ee2e01085dc9346377f57572c5b03876

**Comment by mvexel** [comment]
hm, not sure under which circumstances this is output.. Perhaps @mmd-osm can shed some light on this?

**Comment by mmd-osm** [comment]
Besides that I don't have the slightest idea what this query is good for, it is way too large for an HTTP GET request with its 108874 bytes. Pretty much _any_ web server accepts around 2000 characters for GET requests, which makes this query about 50 times larger than what is technically possible. Using HTTP POST is an absolute must for such monster queries.

**Comment by matkoniecz** [comment]
> I don't really know what this query is good for

It was used to find some still present tagging errors (query was automatically generated from initial list of issues).

**Comment by mvexel** [comment]
I have captured defaulting to POST in #91. If that does not capture this case, I'm going to chalk it up as an outlier :)

**Comment by matkoniecz** [comment]
I would expect #91 to solve this.
