### ISSUE TITLE
Example code in readme broken

### ISSUE THREAD

**Issue by scruss** [mvexel/overpass-api-python-wrapper#85]
When I try 

    print( [(feature['tags']['name'], feature['id']) for feature in response['elements']] )

I get the error

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    KeyError: 'elements'

This works, though:

    print( [(feature['properties']['name'], feature['id']) for feature in response['features']] )

**Comment by mvexel** [comment]
The readme was fixed. Thanks for reporting.
