### ISSUE TITLE
Unnecessary `(._;>;);`

### ISSUE THREAD

**Issue by kitman0804** [mvexel/overpass-api-python-wrapper#92]
The following query doesn't work unless `(._;>;);` is added, but it is not necessary (if I just want way data).

    resp = api.get('rel(3676782);map_to_area->.lantauisland;way(area.lantauisland);')

Error message:
>Traceback (most recent call last):
>  File "python", line 1, in <module>
>UnboundLocalError: local variable 'geometry' referenced before assignment

The problem also occurs for relations.

Note that [http://overpass-api.de/api/interpreter?data=[out:json];rel(3676782);map_to_area->.lantauisland;rel(area.lantauisland);out;](http://overpass-api.de/api/interpreter?data=[out:json];rel(3676782);map_to_area->.lantauisland;way(area.lantauisland);out;) does return a json of way data.

**Comment by mvexel** [comment]
If you amend the query to specify the response format as JSON, you should be fine.

```
>>> resp = api.get('rel(3676782);map_to_area->.lantauisland;way(area.lantauisland);', responseformat="json")
```

Let me know if that works!
