### ISSUE TITLE
Is there a possibility to query a local Overpass db?

### ISSUE THREAD

**Issue by Erhanjinn** [mvexel/overpass-api-python-wrapper#94]
Hi,

is there a possibility to query a local .osm copy of data? Can I make the Overpass API to switch to local a db? Therefore not to make HTTP requests over the internet?

Thanks!

**Comment by tbolender** [comment]
I am afraid this is not possible. The library requires a running server which parses and processes the query. However, you could run a local Overpass instance using your files. For more information about the installation see [here](https://wiki.openstreetmap.org/wiki/Overpass_API/Installation).
